# Generated by Django 3.1 on 2020-10-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0002_auto_20201016_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='log_user_id',
        ),
        migrations.AddField(
            model_name='timelog',
            name='api_token',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
