# Generated by Django 3.1 on 2020-10-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0003_auto_20201017_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelog',
            old_name='log_timestamp',
            new_name='start_timestamp',
        ),
        migrations.AddField(
            model_name='timelog',
            name='end_timestamp',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
